In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#Define the vocabulary size

voc_size=10000

In [5]:
## One Hot Representation for every word

one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[5887, 4138, 6754, 403],
 [5887, 4138, 6754, 7427],
 [5887, 441, 6754, 7777],
 [9177, 8157, 2799, 7859, 4725],
 [9177, 8157, 2799, 7859, 540],
 [1855, 5887, 6518, 6754, 8276],
 [2214, 8703, 4060, 7859]]

In [6]:
#WOrd Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences   #To make all sent to equal size
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5887 4138 6754  403]
 [   0    0    0    0 5887 4138 6754 7427]
 [   0    0    0    0 5887  441 6754 7777]
 [   0    0    0 9177 8157 2799 7859 4725]
 [   0    0    0 9177 8157 2799 7859  540]
 [   0    0    0 1855 5887 6518 6754 8276]
 [   0    0    0    0 2214 8703 4060 7859]]


In [8]:
#Feature representation
dim=10

In [9]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,   # Vocabulary size
                    output_dim=dim,     # Embedding dimension
                    input_length=sent_length))  # Length of input sequences

# Compile the model
model.compile(optimizer='adam', loss='mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 395ms/step


array([[[-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
         -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
         -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
         -1.71531327e-02],
        [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
         -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
         -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
         -1.71531327e-02],
        [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
         -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
         -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
         -1.71531327e-02],
        [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
         -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
         -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
         -1.71531327e-02],
        [-3.50011215e-02,  3.94928455e-03, -3.96253914e-03,
         -5.22356108e-03, -2.75291558e-02, -3.63487378e-02,
         -1.70515850e-03,  1.09405443e-03, -4.001525

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 5887, 4138, 6754,  403])

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 220ms/step


array([[-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
        -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
        -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
        -1.71531327e-02],
       [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
        -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
        -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
        -1.71531327e-02],
       [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
        -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
        -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
        -1.71531327e-02],
       [-1.20628849e-02,  1.89495198e-02,  3.20609473e-02,
        -2.71020774e-02, -1.99957024e-02, -1.77268162e-02,
        -1.79367550e-02,  1.71778351e-03, -1.09069236e-02,
        -1.71531327e-02],
       [-3.50011215e-02,  3.94928455e-03, -3.96253914e-03,
        -5.22356108e-03, -2.75291558e-02, -3.63487378e-02,
        -1.70515850e-03,  1.09405443e-03, -4.00152579e-02,
         3.